version: '3'

services:
  mkdocs:
    container_name: mkdocs
    hostname: mkdocs
    image: squidfunk/mkdocs-material:latest
    ports: 
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ${PWD}:/docs